name: Push Tag to NPM

on:
  push:
    tags:
      - 'v*'
    branches:
      - feature/tag-release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: ./.github/actions/build
  publish-docs:
    name: Documentation
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: ./.github/actions/docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish-github-pages:
    name: Github Pages
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: ./.github/actions/github-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish-npm-package:
    name: Publish NPM
    needs: [publish-docs, publish-github-pages]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: ./.github/actions/publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
